### ISSUE TITLE
The installation of tez is crached

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-getting-started#142]
ASK [tosit.tdp.common : Put tez release to hdfs] ****************************************************************************************************************************************************************
fatal: [edge-01]: FAILED! => changed=false
  cmd:
  - /opt/tdp/hadoop/bin/hdfs
  - --config
  - /etc/hadoop/conf
  - dfs
  - -put
  - /tmp/tez-0.9.1-TDP-0.1.0-SNAPSHOT.tar.gz
  - /tdp/tez
  delta: '0:00:02.014711'
  end: '2022-07-08 12:23:18.278058'
  failed_when_result: true
  msg: non-zero return code
  rc: 1
  start: '2022-07-08 12:23:16.263347'
  stderr: |-
    2022-07-08 12:23:17,831 WARN hdfs.DataStreamer: DataStreamer Exception
    org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /tdp/tez/tez-0.9.1-TDP-0.1.0-SNAPSHOT.tar.gz._COPYING_ could only be written to 0 of the 1 minReplication nodes. There are 0 datanode(s) running and no node(s) are excluded in this operation.
            at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2117)
            at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:287)
            at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2691)
            at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
            at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
            at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
            at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
            at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
            at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
            at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
            at java.security.AccessController.doPrivileged(Native Method)
            at javax.security.auth.Subject.doAs(Subject.java:422)
            at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
            at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)

            at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1497)
            at org.apache.hadoop.ipc.Client.call(Client.java:1443)
            at org.apache.hadoop.ipc.Client.call(Client.java:1353)
            at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
            at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
            at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
            at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:510)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
            at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
            at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
            at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
            at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
            at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
            at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1078)
            at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
            at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
            at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
    put: File /tdp/tez/tez-0.9.1-TDP-0.1.0-SNAPSHOT.tar.gz._COPYING_ could only be written to 0 of the 1 minReplication nodes. There are 0 datanode(s) running and no node(s) are excluded in this operation.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by mehdibn** [comment]
You are always right @rpignolet :) !

Indeed, your datanodes are not working as expected, you have to fix this issue, then, continue your deployment ..

**Comment by taabich** [comment]
Thank you for your help!
The problem is resolved by formating hdfs
Best regards

**Comment by taabich** [comment]
Thank you for your help!
The problem is resolved by formating hdfs
Best regards
