### ISSUE TITLE
Starting tdp-ui fail

### ISSUE THREAD

**Issue by EmmanuelVinet33** [TOSIT-IO/tdp-getting-started#264]
Hye,
Running npm instruction to run the tdp-ui is failing, any idea ?
Thanks.
Emmanel
`
$ npm --prefix ./tdp-ui run dev --show-all

> tdp-ui@0.0.0 dev
> next dev

/home/vinet/git/tdp-getting-started/node_modules/next/dist/cli/next-dev.js:261
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/vinet/git/tdp-getting-started/node_modules/next/dist/lib/commands.js:15:30)
    at Object.<anonymous> (/home/vinet/git/tdp-getting-started/node_modules/next/dist/bin/next:144:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
`

**Comment by PaulFarault** [comment]
Hi!

What Node.js version are you using?

**Comment by EmmanuelVinet33** [comment]
Node version : v12.22.9
npm version : 8.5.1
On Ubuntu 22.04

**Comment by EmmanuelVinet33** [comment]
Thanks, this part is solved, the UI is working.
